### ISSUE TITLE
NPM still holds Version 0.6.2

### ISSUE THREAD

**Issue by hcomnetworkers** [ekristen/dns-proxy#42]
Could you please push the latest release to NPM? It still has 0.6.2.

**Comment by ekristen** [comment]
I need to take a look at updating the dependencies and then I'll look at pushing. I'm also considering discontinuing this in favor of CoreDNS.

It's a super lightweight DNS server that can be used as a proxy and is highly extensible.  I built this originally because the existing tooling at the time was dreadful.

**Comment by whitecolor** [comment]
@ekristen 
Well still it is better to publish latest version.

**Comment by ekristen** [comment]
NPM 1.1.0 is now published.
